### ISSUE TITLE
Adding functionality to trigger platform plugins from the console.

### ISSUE THREAD

**Issue by Xenowa** [ballerina-platform/static-code-analysis-tool#18]
### Description:

Currently, the scan tool supports reporting analysis results to platform plugins if they are defined in a `Scan.toml` file as follows and when the `bal scan` command is run:

```toml
[[platform]]
name = "platformName"
path = "path/to/platformPlugin"
```

It would be ideal to trigger reporting analysis results to platform plugins via simply running `bal scan --platforms="platformName"`, where the scan tool downloads the relevant platform plugin JAR and passes the analysis results to it.
